### ISSUE TITLE
print(options) function throws an exception on non Mac devices

### ISSUE THREAD

**Issue by LEQADA** [tabrindle/envinfo#3]
## Expected behavior 
`envinfo.print(options)`
Should print a result without any errors. For instance like this on some Linux machine

```
Environment:
  OS:  Linux 4.9
  Node:  8.7.0
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  Not Found
```

## Current behavior
On non Mac devices the function throws an exception
```
Environment:
  OS:  Linux 4.9
  Node:  8.7.0
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  Not Found
Error: unable to print environment info
{ Error: not found: xcodebuild
    at getNotFoundError (/home/user/Desktop/AwesomeProject/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/home/user/Desktop/AwesomeProject/node_modules/which/which.js:134:9)
    at getXcodeVersion (/home/user/Desktop/AwesomeProject/node_modules/envinfo/envinfo.js:17:25)
    at Object.module.exports.print (/home/user/Desktop/AwesomeProject/node_modules/envinfo/envinfo.js:137:28)
    at Object.info (/home/user/Desktop/AwesomeProject/node_modules/react-native/local-cli/info/info.js:17:13)
    at Promise.resolve.then (/home/user/Desktop/AwesomeProject/node_modules/react-native/local-cli/cliEntry.js:109:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16) code: 'ENOENT' }
```

Related issue https://github.com/facebook/react-native/issues/16496

**Comment by tabrindle** [comment]
Thanks for the PR!
